import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, paddingTop: 0 },
  contentContainer: { paddingBottom: 20 },
  backButton: { padding: 16, paddingBottom: 8 },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  loadingText: { marginTop: 12 },
  error: { fontSize: 16 },
  header: { alignItems: "center", marginBottom: 24, gap: 8, paddingHorizontal: 16 },
  name: { fontSize: 22, fontWeight: "700" },
  card: {
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    marginHorizontal: 16,
    elevation: 3,
  },
  row: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 12 },
  value: { fontSize: 15 },
  sectionTitleContainer: { paddingHorizontal: 16 },
  sectionTitle: { fontSize: 16, fontWeight: "700", marginBottom: 8 },
  pedido: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 8 },
  pedidoText: { fontSize: 14 },
  empty: { fontSize: 14, textAlign: "center" },
  editButton: {
    paddingVertical: 14,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    marginHorizontal: 16,
  },
  editText: { color: "#ffffff", fontWeight: "800", fontSize: 16 },
  deleteButton: {
    paddingVertical: 14,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    marginHorizontal: 16,
    backgroundColor: "#ef4444",
  },
  deleteText: { color: "#ffffff", fontWeight: "800", fontSize: 16 },
});
